require('dotenv').config();
const mongoose = require('mongoose');
const Tour = require('./models/Tour');

const tours = [
  { title: 'Golden Triangle', slug: 'golden-triangle', img: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80', price: '₹12,500/person', days: '5 Days Tour', location: 'Delhi, Agra & Jaipur, India', category: 'Culture', features: ['🚿 2', '🛏 3', '🏛 Heritage'], description: 'Experience the iconic Golden Triangle covering Delhi, Agra, and Jaipur.', highlights: ['Taj Mahal sunrise visit', 'Red Fort & Qutub Minar', 'Amber Fort elephant ride', 'Hawa Mahal & City Palace', 'Local bazaar shopping'], includes: ['Hotel accommodation (4 nights)', 'Daily breakfast', 'AC transport', 'Expert guide', 'Entry tickets'], itinerary: [{ day: 1, title: 'Arrive Delhi', desc: 'Check-in, Red Fort & Qutub Minar visit.' }, { day: 2, title: 'Delhi to Agra', desc: 'Drive to Agra, Taj Mahal at sunset.' }, { day: 3, title: 'Agra to Jaipur', desc: 'Agra Fort, then drive to Jaipur.' }, { day: 4, title: 'Jaipur Sightseeing', desc: 'Amber Fort, Hawa Mahal, City Palace.' }, { day: 5, title: 'Departure', desc: 'Return to Delhi, departure.' }] },
  { title: 'Goa Beach Getaway', slug: 'goa-beach-getaway', img: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80', price: '₹8,999/person', days: '4 Days Tour', location: 'Goa, India', category: 'Beach', features: ['🚿 2', '🛏 2', '🏖 Near Beach'], description: 'Relax on the sun-kissed beaches of Goa.', highlights: ['North & South Goa beaches', 'Water sports & parasailing', 'Old Goa churches', 'Sunset cruise', 'Seafood dining'], includes: ['Beach resort (3 nights)', 'Daily breakfast', 'Airport transfers', 'Sightseeing tour', 'Sunset cruise'], itinerary: [{ day: 1, title: 'Arrive Goa', desc: 'Check-in, relax at Calangute Beach.' }, { day: 2, title: 'North Goa', desc: 'Water sports, Fort Aguada, Baga Beach.' }, { day: 3, title: 'South Goa & Heritage', desc: 'Old Goa churches, Palolem Beach, sunset cruise.' }, { day: 4, title: 'Departure', desc: 'Leisure morning, transfer to airport.' }] },
  { title: 'Kerala Backwaters', slug: 'kerala-backwaters', img: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80', price: '₹15,000/person', days: '7 Days Tour', location: 'Alleppey, Kerala, India', category: 'Nature', features: ['🚿 2', '🛏 3', '🌿 Nature'], description: "Cruise through the serene backwaters of Kerala on a traditional houseboat.", highlights: ['Houseboat stay in Alleppey', 'Munnar tea gardens', 'Periyar Wildlife Sanctuary', 'Kovalam Beach', 'Kathakali performance'], includes: ['Houseboat (1 night)', 'Hotel (5 nights)', 'All meals on houseboat', 'AC transport', 'Wildlife safari'], itinerary: [{ day: 1, title: 'Arrive Kochi', desc: 'Check-in, Fort Kochi & Chinese fishing nets.' }, { day: 2, title: 'Kochi to Munnar', desc: 'Drive through tea estates.' }, { day: 3, title: 'Munnar', desc: 'Tea museum, Eravikulam National Park.' }, { day: 4, title: 'Munnar to Thekkady', desc: 'Periyar Wildlife Sanctuary boat ride.' }, { day: 5, title: 'Thekkady to Alleppey', desc: 'Spice plantation, houseboat check-in.' }, { day: 6, title: 'Alleppey to Kovalam', desc: 'Backwater cruise, drive to Kovalam Beach.' }, { day: 7, title: 'Departure', desc: 'Trivandrum sightseeing, departure.' }] },
  { title: 'Ladakh Adventure', slug: 'ladakh-adventure', img: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80', price: '₹18,500/person', days: '8 Days Tour', location: 'Leh-Ladakh, India', category: 'Adventure', features: ['🚿 1', '🛏 2', '⛰ Near Mountain'], description: 'Embark on an epic high-altitude adventure in Ladakh.', highlights: ['Pangong Lake', 'Khardung La Pass', 'Nubra Valley camel ride', 'Thiksey & Hemis Monastery', 'Magnetic Hill'], includes: ['Hotel & camping (7 nights)', 'All meals', 'Bike/jeep rental', 'Inner line permits', 'Expert guide'], itinerary: [{ day: 1, title: 'Arrive Leh', desc: 'Acclimatization day, local market.' }, { day: 2, title: 'Leh Monasteries', desc: 'Thiksey, Hemis, Shey Palace.' }, { day: 3, title: 'Leh to Nubra Valley', desc: 'Cross Khardung La, camel ride at Hunder.' }, { day: 4, title: 'Nubra to Pangong', desc: 'Drive to Pangong Lake, overnight camp.' }, { day: 5, title: 'Pangong Lake', desc: 'Sunrise at lake, explore surroundings.' }, { day: 6, title: 'Pangong to Leh', desc: 'Return via Chang La pass.' }, { day: 7, title: 'Magnetic Hill & Confluence', desc: 'Indus-Zanskar confluence, Magnetic Hill.' }, { day: 8, title: 'Departure', desc: 'Transfer to Leh airport.' }] },
  { title: 'Varanasi Spiritual Tour', slug: 'varanasi-spiritual-tour', img: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80', price: '₹9,500/person', days: '5 Days Tour', location: 'Varanasi, Uttar Pradesh, India', category: 'Culture', features: ['🚿 2', '🛏 2', '🏛 Heritage'], description: 'Immerse yourself in the spiritual heart of India.', highlights: ['Ganga Aarti at Dashashwamedh Ghat', 'Sunrise boat ride', 'Sarnath Buddhist site', 'Kashi Vishwanath Temple', 'Old city walk'], includes: ['Hotel (4 nights)', 'Daily breakfast', 'Boat rides', 'Guide', 'Sarnath excursion'], itinerary: [{ day: 1, title: 'Arrive Varanasi', desc: 'Check-in, evening Ganga Aarti.' }, { day: 2, title: 'Ghats & Temples', desc: 'Sunrise boat ride, Kashi Vishwanath.' }, { day: 3, title: 'Sarnath', desc: 'Buddhist stupas, Dhamek Stupa, museum.' }, { day: 4, title: 'Old City Walk', desc: 'Narrow lanes, silk weaving, local cuisine.' }, { day: 5, title: 'Departure', desc: 'Morning aarti, transfer to station/airport.' }] },
  { title: 'Manali Snow Escape', slug: 'manali-snow-escape', img: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?w=800&q=80', price: '₹11,000/person', days: '6 Days Tour', location: 'Manali, Himachal Pradesh, India', category: 'Adventure', features: ['🚿 2', '🛏 3', '⛰ Near Mountain'], description: 'Escape to the snow-capped peaks of Manali.', highlights: ['Rohtang Pass snow activities', 'Solang Valley skiing', 'Beas River rafting', 'Hadimba Temple', 'Old Manali cafes'], includes: ['Hotel (5 nights)', 'Daily breakfast', 'AC transport', 'Adventure activities', 'Guide'], itinerary: [{ day: 1, title: 'Arrive Manali', desc: 'Check-in, Mall Road & Hadimba Temple.' }, { day: 2, title: 'Solang Valley', desc: 'Skiing, zorbing, paragliding.' }, { day: 3, title: 'Rohtang Pass', desc: 'Snow activities, scenic views.' }, { day: 4, title: 'River Rafting', desc: 'Beas River rafting, Old Manali.' }, { day: 5, title: 'Naggar & Kullu', desc: 'Naggar Castle, Kullu Shawl factory.' }, { day: 6, title: 'Departure', desc: 'Transfer to Bhuntar airport/bus stand.' }] },
  { title: 'Andaman Islands', slug: 'andaman-islands', img: 'https://images.unsplash.com/photo-1586500036706-41963de24d8b?w=800&q=80', price: '₹7,500/person', days: '4 Days Tour', location: 'Port Blair, Andaman, India', category: 'Beach', features: ['🚿 2', '🛏 2', '🏖 Near Beach'], description: 'Discover the pristine beaches and crystal-clear waters of the Andaman Islands.', highlights: ['Radhanagar Beach', 'Scuba diving & snorkeling', 'Cellular Jail light & sound show', 'Havelock Island', 'Glass-bottom boat ride'], includes: ['Hotel (3 nights)', 'Daily breakfast', 'Ferry tickets', 'Water sports', 'Sightseeing'], itinerary: [{ day: 1, title: 'Arrive Port Blair', desc: 'Cellular Jail, light & sound show.' }, { day: 2, title: 'Havelock Island', desc: 'Ferry to Havelock, Radhanagar Beach.' }, { day: 3, title: 'Water Sports', desc: 'Scuba diving, snorkeling, glass-bottom boat.' }, { day: 4, title: 'Departure', desc: 'Return to Port Blair, departure.' }] },
  { title: 'Rajasthan Desert Safari', slug: 'rajasthan-desert-safari', img: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80', price: '₹13,000/person', days: '6 Days Tour', location: 'Jaisalmer, Rajasthan, India', category: 'Adventure', features: ['🚿 1', '🛏 2', '🌅 Desert'], description: 'Ride camels across the golden Thar Desert.', highlights: ['Jaisalmer Fort', 'Sam Sand Dunes camel safari', 'Luxury desert camp stay', 'Patwon Ki Haveli', 'Folk music & dance'], includes: ['Hotel & desert camp (5 nights)', 'Daily breakfast & dinner', 'Camel safari', 'Jeep safari', 'Cultural evening'], itinerary: [{ day: 1, title: 'Arrive Jaisalmer', desc: 'Check-in, Jaisalmer Fort exploration.' }, { day: 2, title: 'City Tour', desc: 'Patwon Ki Haveli, Gadisar Lake.' }, { day: 3, title: 'Sam Sand Dunes', desc: 'Camel safari, sunset, desert camp stay.' }, { day: 4, title: 'Khuri Dunes', desc: 'Jeep safari, folk music evening.' }, { day: 5, title: 'Jodhpur Day Trip', desc: 'Mehrangarh Fort, Jaswant Thada.' }, { day: 6, title: 'Departure', desc: 'Transfer to Jaisalmer airport/station.' }] },
  { title: 'Coorg Coffee Trails', slug: 'coorg-coffee-trails', img: 'https://images.unsplash.com/photo-1580889240911-ced85d8b3b37?w=800&q=80', price: '₹10,500/person', days: '5 Days Tour', location: 'Coorg, Karnataka, India', category: 'Nature', features: ['🚿 2', '🛏 3', '🌿 Nature'], description: "Walk through misty coffee and spice plantations in the Scotland of India.", highlights: ['Coffee plantation walk', 'Abbey Falls trek', "Raja's Seat viewpoint", 'Namdroling Monastery', 'Coorg cuisine experience'], includes: ['Plantation resort (4 nights)', 'Daily breakfast', 'Plantation tour', 'Trekking guide', 'Transport'], itinerary: [{ day: 1, title: 'Arrive Coorg', desc: "Check-in, Raja's Seat sunset." }, { day: 2, title: 'Coffee Plantation', desc: 'Guided plantation walk, spice garden.' }, { day: 3, title: 'Waterfalls & Monastery', desc: 'Abbey Falls, Namdroling Monastery.' }, { day: 4, title: 'Trekking', desc: 'Tadiandamol peak trek.' }, { day: 5, title: 'Departure', desc: 'Local market, transfer to Mysore/Bangalore.' }] },
  { title: 'Darjeeling & Sikkim', slug: 'darjeeling-sikkim', img: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80', price: '₹14,000/person', days: '7 Days Tour', location: 'Darjeeling, West Bengal, India', category: 'Nature', features: ['🚿 2', '🛏 2', '⛰ Near Mountain'], description: 'Ride the iconic toy train and watch sunrise over Kanchenjunga.', highlights: ['Tiger Hill sunrise', 'Darjeeling Toy Train', 'Rumtek Monastery', 'Tsomgo Lake', 'Tea garden visit'], includes: ['Hotel (6 nights)', 'Daily breakfast', 'Toy train ticket', 'Permits', 'Transport'], itinerary: [{ day: 1, title: 'Arrive Darjeeling', desc: 'Check-in, Mall Road, tea garden.' }, { day: 2, title: 'Tiger Hill & Toy Train', desc: 'Sunrise at Tiger Hill, toy train ride.' }, { day: 3, title: 'Darjeeling to Gangtok', desc: 'Drive to Gangtok, Rumtek Monastery.' }, { day: 4, title: 'Gangtok Sightseeing', desc: 'MG Marg, Enchey Monastery.' }, { day: 5, title: 'Tsomgo Lake', desc: 'Tsomgo Lake & Baba Mandir excursion.' }, { day: 6, title: 'Pelling', desc: 'Pemayangtse Monastery, Kanchenjunga views.' }, { day: 7, title: 'Departure', desc: 'Transfer to NJP/Bagdogra.' }] },
  { title: 'Spiti Valley Expedition', slug: 'spiti-valley-expedition', img: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&q=80', price: '₹16,500/person', days: '8 Days Tour', location: 'Spiti, Himachal Pradesh, India', category: 'Adventure', features: ['🚿 1', '🛏 2', '⛰ Near Mountain'], description: 'Journey through the cold desert of Spiti Valley.', highlights: ['Key Monastery', 'Chandratal Lake', 'Kaza & Kibber village', 'Pin Valley National Park', 'Kunzum Pass'], includes: ['Hotel & homestay (7 nights)', 'All meals', '4WD transport', 'Inner line permits', 'Guide'], itinerary: [{ day: 1, title: 'Shimla to Narkanda', desc: 'Drive through apple orchards.' }, { day: 2, title: 'Narkanda to Kaza', desc: 'Cross Jalori Pass, enter Spiti.' }, { day: 3, title: 'Kaza Sightseeing', desc: 'Key Monastery, Kibber village.' }, { day: 4, title: 'Pin Valley', desc: 'Pin Valley National Park, Mud village.' }, { day: 5, title: 'Chandratal Lake', desc: 'Trek to Chandratal, overnight camp.' }, { day: 6, title: 'Kunzum Pass to Manali', desc: 'Cross Kunzum Pass, arrive Manali.' }, { day: 7, title: 'Manali', desc: 'Rest day, Old Manali exploration.' }, { day: 8, title: 'Departure', desc: 'Transfer to Bhuntar airport.' }] },
  { title: 'Pondicherry Coastal Tour', slug: 'pondicherry-coastal-tour', img: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80', price: '₹8,000/person', days: '4 Days Tour', location: 'Pondicherry, India', category: 'Beach', features: ['🚿 2', '🛏 2', '🏖 Near Beach'], description: 'Explore the French colonial charm of Pondicherry.', highlights: ['French Quarter walk', 'Sri Aurobindo Ashram', 'Auroville Matrimandir', 'Paradise & Promenade Beach', 'French-Indian cuisine'], includes: ['Boutique hotel (3 nights)', 'Daily breakfast', 'City tour', 'Auroville visit', 'Transport'], itinerary: [{ day: 1, title: 'Arrive Pondicherry', desc: 'French Quarter, Promenade Beach.' }, { day: 2, title: 'Ashram & Auroville', desc: 'Sri Aurobindo Ashram, Auroville Matrimandir.' }, { day: 3, title: 'Beaches & Cuisine', desc: 'Paradise Beach, French-Indian food trail.' }, { day: 4, title: 'Departure', desc: 'Morning yoga, transfer to Chennai.' }] },
];

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    await Tour.deleteMany({});
    await Tour.insertMany(tours);
    console.log(`✅ Seeded ${tours.length} tours into pacific DB`);
    process.exit(0);
  })
  .catch(err => { console.error(err); process.exit(1); });
